# Generated by Django 5.0.6 on 2024-06-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('body', models.CharField(blank=True, max_length=300, null=True)),
                ('summary', models.CharField(blank=True, max_length=60, null=True)),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
